# Generated by Django 5.2.13 on 2026-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpose',
            name='map_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
